server:
  port: 8004
eureka:
  instance:
    instance-id: could-article
    appname: ${spring.application.name}
    hostname: 47.92.212.216
    port: 8001
  client: 
    service-url: 
         defaultZone: http://admin:wdgcould@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
profiles:
  dev
spring:
  application:
    name: could-article
